# Usar a opcao 'ansible-playbook --tags agent' para instalacao nos agentes
# Playbook automaticamente irá instalar zabbix server e zabbix agent
---
- hosts: all
  become: True
  roles:
    - role: zabbix-agentd
