# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_API_VERSION = 2

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.ssh.insert_key = false


  config.vm.define 'Server' do |centos701|
    centos701.vm.network "private_network", ip: "192.168.56.10"
    centos701.vm.box = 'bento/centos-7.2'
    centos701.vm.provision 'shell', inline: <<-SHELL
      sudo hostnamectl set-hostname server01
      sudo yum clean all
      sudo yum install -y epel-release
      sudo ifconfig enp0s8 192.168.56.10
      reboot
    SHELL
  end
end

