---
    - name: Install Zabbix Agent
      yum:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - zabbix-agent.x86_64
      notify:
        - restart zabbix-agent   
      tags: agent 

    - name: Remove file
      file:
        path: /etc/zabbix/zabbix_agentd.conf
        state: absent

    - name: Copy File Auth Agent
      template:
        src: templates/zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
        owner: zabbix
        group: zabbix
        mode: 0640
        force: yes
      tags: agent
